name: CI - Test with RabbitMQ

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:4-management
        ports:
          - 5672:5672 # Default RabbitMQ port
          - 15672:15672 # Management UI port
        options: >-
          --health-cmd "rabbitmqctl status"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Wait for RabbitMQ to be ready
        run: |
          for i in {1..10}; do
            if docker exec $(docker ps -q -f ancestor=rabbitmq:3-management) rabbitmqctl status &> /dev/null; then
              echo "RabbitMQ is ready"
              break
            fi
            echo "Waiting for RabbitMQ..."
            sleep 5
          done

      - name: Create virtual host
        run: |
          docker exec $(docker ps -q -f ancestor=rabbitmq:3-management) rabbitmqctl add_vhost my_vhost
          docker exec $(docker ps -q -f ancestor=rabbitmq:3-management) rabbitmqctl set_permissions -p my_vhost guest ".*" ".*" ".*"

      - name: Run tests
        env:
          AMQP_ADDR: amqp://guest:guest@localhost:5672/my_vhost
        run: cargo test -- --test-threads=1
